# Site settings
  # Note: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.
  # When filling this file in, below, be sure to DELETE the "#" comments 

#content for nav.html
title: RadioMe
subtitle: Adaptive Radio for People with Dementia

#content for index.html
  #Add your own info, deleting the comments "#". This data automatically writes to the Index page's mini, about section.
greeting: RadioMe #GREETING_GOES_HERE 
logo_img: /assets/img/RadioMe-logo.png #LOGO_IMG_SRC_GOES_HERE | default: /assets/img/placehold.png
subgreeting_one: Personalised radio for people with dementia #SUBGREETING_ONE_GOES_HERE
subgreeting_two: #SUBGREETING_TWO_GOES_HERE

# Again: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.

#content for nav.html (shown on desktop) navigation links
nav_link_one_name: Interdisplinary Centre for Computer Music Research, University of Plymouth 
nav_link_one_link: http://cmr.soc.plymouth.ac.uk/ 
nav_link_two_name: Cambridge Institute for Music Therapy Research, Anglia Ruskin University
nav_link_two_link: https://aru.ac.uk/cambridge-institute-for-music-therapy-research #"/categories"
nav_link_three_name: GIST, Computer Science, Glasgow University #NAV_NAME_GOES_HERE
nav_link_three_link: https://www.gla.ac.uk/schools/computing/research/researchsections/gist-section/ #NAV_LINK_GOES_HERE

#content for footer.html (shown on mobile) footer navigation links
footer_link_one_name: Interdisplinary Centre for Computer Music Research, University of Plymouth 
footer_link_one_link: http://cmr.soc.plymouth.ac.uk/ 
footer_link_two_name: Cambridge Institute for Music Therapy Research, Anglia Ruskin University
footer_link_two_link: https://aru.ac.uk/cambridge-institute-for-music-therapy-research #"/categories"
footer_link_three_name: GIST, Computer Science, Glasgow University #NAV_NAME_GOES_HERE
footer_link_three_link: https://www.gla.ac.uk/schools/computing/research/researchsections/gist-section/ #NAV_LINK_GOES_Here 

# footer_link_one_name: #FOOTER_NAME_GOES_HERE
# footer_link_one_link: #FOOTER_LINK_GOES_HERE

# footer_link_two_name: Categories
# footer_link_two_link: "/categories"

# footer_link_three_name: #FOOTER_NAME_GOES_HERE
# footer_link_three_link: #FOOTER_LINK_GOES_HERE

baseurl: ""
google_tracking_id: #deletme-Google Analytics Tracking ID- UA-XXXXXXXX-X
copyright_name: RadioMe project

# SEO data (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/img/simpol-favicon.png
description: This is the website for the RadioMe Project
author:
  name: Dave Moffat
  email: david.moffat@plymouth.ac.uk
  twitter: djmoffat

social:
  name: RadioMe Project
  links:
    - https://twitter.com/
    - https://github.com/Radio-Me

# Build settings
permalink: pretty
paginate: 12

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- vendor
