# Site settings
  # Note: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.
  # When filling this file in, below, be sure to DELETE the "#" comments 

#content for nav.html
title: RadioMe
subtitle: Adaptive Radio for People with Dementia

#content for index.html
  #Add your own info, deleting the comments "#". This data automatically writes to the Index page's mini, about section.
greeting: RadioMe #GREETING_GOES_HERE 
logo_img: /assets/img/RadioMe-logo.png #LOGO_IMG_SRC_GOES_HERE | default: /assets/img/placehold.png
subgreeting_one: Personalised radio for people with dementia #SUBGREETING_ONE_GOES_HERE
subgreeting_two: #SUBGREETING_TWO_GOES_HERE

# Again: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.

#content for nav.html (shown on desktop) navigation links
nav_link:
 - name: Categories #Interdisplinary Centre for Computer Music Research, University of Plymouth 
   url: /categories
 - name: Publications
   url: /publications
 - name: People
   url: /people
 - name: About The Project
   url: /about-us
 - name: Contact Us
   url: /contact-us


baseurl: ""
google_tracking_id: #deletme-Google Analytics Tracking ID- UA-XXXXXXXX-X
copyright_name: RadioMe project

# SEO data (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/img/simpol-favicon.png
description: This is the website for the RadioMe Project
author:
  name: Dave Moffat
  email: david.moffat@plymouth.ac.uk
  twitter: djmoffat

social:
  name: RadioMe Project
  links:
    - https://twitter.com/djmoffat
    - https://github.com/Radio-Me

# Build settings
permalink: pretty
paginate: 12

defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true

scholar:
  source: publications
  bibliography: publications.bib

# scholar:
#   style: mla
  # sort_by: year
  # order: descending
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-scholar
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- vendor
